Use LDFLAGS for host binaries
Distributions bring their own sets of LDFLAGS, and some fail when
binaries do not match their expectation after ignoring those flags.

Eg. for yocto:

 ERROR: optee-examples-3.12.0+gitAUTOINC+9a755dcf4d-r0 do_package_qa: QA Issue: File /usr/bin/optee_example_secure_storage in package optee-examples doesn't have GNU_HASH (didn't pass LDFLAGS?)
 File /usr/bin/optee_example_acipher in package optee-examples doesn't have GNU_HASH (didn't pass LDFLAGS?)
 ...

Signed-off-by: Yann Dirson <yann@blade-group.com>
Reviewed-by: Jerome Forissier <jerome@forissier.org>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>