sstorage: fix unused parameter error messages
Fix errors when trying to build the secure storage host application
using AOSP.

  error: unused parameter 'argc' [-Werror,-Wunused-parameter]
  error: unused parameter 'argv' [-Werror,-Wunused-parameter]

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>